### ISSUE TITLE
missing search2.py

### ISSUE THREAD

**Issue by JimCornelius** [h-nasir/PyQtChess#1]
Hi. This is very good. I'm using it to help with me re-remembering how to use PyQt. I was thinking of doing a basic chess program and this came up in a search.

search2.py seems to be missing but doesn't seem to affect self-play.

**Comment by h-nasir** [comment]
The intention behind the self_play.py file is not to be used during the actual program, but to compare two different search algorithms through self-play to determine which performs better. As it stands this is mostly a manual process.

The correct way to use this would be to create a copy of the search.py file, named search2.py. In this file you would make the desired changes to the Search class which you wish to compare against the original. With both of these files in the root directory, self_play.py should run successfully. The program will continue to self-play until you manually exit, outputting the cumulative results to the console after each game is completed.
